name: Sync multiple branches
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> git-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: git-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}